name: Myfirst CI
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: echo "Hello World"
      - name: Get the docker version
        run: docker -version
        
